name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 */3 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      IMAGE_NAME: emby_pinyin
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Get Description
        id: description
        run: |
          Description=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/DDS-Derek/emby_pinyin-Docker | \
            jq -r ".description")
          echo "Description=${Description}"
          echo "Description=${Description}" >> $GITHUB_OUTPUT

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/386
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
            linux/ppc64le
            linux/s390x
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      -
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          short-description: ${{ steps.description.outputs.Description }}
          readme-filepath: ./README.md